name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - uses: pnpm/action-setup@v2
       with:
         version: 8

      # Restart the server
     - name: Restart server
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: cd ${{ vars.REMOTE_PATH }} && ./restart.sh
